### PR TITLE
* Lexer.has: return true for error token, if any (fixes #76).

### LINKED ISSUE #76: Lexer.has does not find error token.
var moo = require('moo');
	var lexer = moo.compile({
		word: /\w+/,
		ws: { match: /\s+/, lineBreaks: true },
		somethingElse: moo.error
	});
	console.log('has word?', lexer.has('word'));
	console.log('has ws?', lexer.has('ws'));
	console.log('has somethingElse?', lexer.has('somethingElse'));

This means that you can't define an error token and use it with Nearley? AFAICT it calls `Lexer.has` on every token that you use. At any rate, if you're going to claim that you can define an error token instead of throwing an error, then it should behave just like any other token in all respects.

### PR DESCRIPTION
**Pull request by JoshuaGrams**

### CODE REVIEW

**Comment by tjvr** [comment]
Thanks for spotting this!

Please can you add a test for this? :-)

**Comment by JoshuaGrams** [comment]
Ooops.  Added tests.

**Comment by tjvr** [comment]
I just realised you're the guy who wrote [Pint-sized Earley Parser](http://joshuagrams.github.io/pep/) :D I really liked that article, wrote a couple of (unshared) parsers based on your ideas, and indeed I'm slowly trying to work them into Nearley... :-)

**Comment by JoshuaGrams** [comment]
Heh. Thanks. Not my ideas, though. That's almost straight out of [Elizabeth Scott's paper](http://www.sciencedirect.com/science/article/pii/S1571066108001497).  Loup Vaillant ([Earley Parsing Explained](http://loup-vaillant.fr/tutorials/earley-parsing/parser)) said that he "completely failed to understand" her paper.  He presents a more complicated (and slower?) algorithm to construct the parse trees.  We had a conversation on the FoNC mailing list and were just talking past each other, so I wrote an implementation to demonstrate how simple it actually is once you strip away all the obfuscating formalisms. Still not sure I actually addressed his objections, but I had fun writing it. :-)

**Pull request merged**
